queue_rules:
  - name: default
    conditions:
      - "-draft"

pull_request_rules:

  - name: Label Scala Steward and Renovate PRs with 'build'
    conditions:
      - or:
        - "author=scala-steward"
        - "author=renovate[bot]"
    actions:
      label:
        add:
          - build

  - name: Automatic merge on approval
    conditions:
      - or:
          - "check-success=typesafe-cla-validator"
          - "author=renovate[bot]"
      - "#changes-requested-reviews-by=0"
      - or:
          - "#approved-reviews-by>=1"
          - "author=scala-steward"
          - "author=nafg"
          - "author=renovate[bot]"
      - and:
        - "check-success=continuous-integration/appveyor/pr"
        - "check-success=General (2.12.15, 8)"
        - "check-success=General (2.12.15, 17)"
        - "check-success=General (2.13.8, 8)"
        - "check-success=General (2.13.8, 17)"
        - "check-success=DB2 (DB2Test, 2.12.15, 8)"
        - "check-success=DB2 (DB2Test, 2.12.15, 17)"
        - "check-success=DB2 (DB2Test, 2.13.8, 8)"
        - "check-success=DB2 (DB2Test, 2.13.8, 17)"
        - "check-success=Oracle (OracleTest, 2.12.15, 8)"
        - "check-success=Oracle (OracleTest, 2.12.15, 17)"
        - "check-success=Oracle (OracleTest, 2.13.8, 8)"
        - "check-success=Oracle (OracleTest, 2.13.8, 17)"
        - "check-success=Postgres (PostgresTest, 2.12.15, 8)"
        - "check-success=Postgres (PostgresTest, 2.12.15, 17)"
        - "check-success=Postgres (PostgresTest, 2.13.8, 8)"
        - "check-success=Postgres (PostgresTest, 2.13.8, 17)"
        - "check-success=SQL Server (SQLServerJTDSTest, 2.12.15, 8)"
        - "check-success=SQL Server (SQLServerJTDSTest, 2.12.15, 17)"
        - "check-success=SQL Server (SQLServerJTDSTest, 2.13.8, 8)"
        - "check-success=SQL Server (SQLServerJTDSTest, 2.13.8, 17)"
        - "check-success=SQL Server (SQLServer2012JTDSTest, 2.12.15, 8)"
        - "check-success=SQL Server (SQLServer2012JTDSTest, 2.12.15, 17)"
        - "check-success=SQL Server (SQLServer2012JTDSTest, 2.13.8, 8)"
        - "check-success=SQL Server (SQLServer2012JTDSTest, 2.13.8, 17)"
        - "check-success=SQL Server (SQLServer2014JTDSTest, 2.12.15, 8)"
        - "check-success=SQL Server (SQLServer2014JTDSTest, 2.12.15, 17)"
        - "check-success=SQL Server (SQLServer2014JTDSTest, 2.13.8, 8)"
        - "check-success=SQL Server (SQLServer2014JTDSTest, 2.13.8, 17)"
        - "check-success=SQL Server (SQLServer2017JTDSTest, 2.12.15, 8)"

    actions:
      queue:
        name: default
        method: merge
        update_method: rebase
